<?php

$indian_bankname_list =["Allahabad Bank",
"Andhra Bank",
"Bank of Baroda",
"Bank of India",
"Bank of Maharashtra",
"Canara Bank",
"Central Bank of India",
"Corporation Bank",
"Dena Bank",
"Indian Bank",
"Indian Overseas Bank",
"IDBI Bank",
"Oriental Bank of Commerce",
"Punjab and Sindh Bank",
"Punjab National Bank",
"State Bank of India",
"Syndicate Bank",
"UCO Bank",
"Union Bank of India",
"United Bank of India",
"Vijaya Bank",
"Axis Bank",
"Bandhan Bank",
"Catholic Syrian Bank",
"City Union Bank",
"DCB Bank",
"Dhanlaxmi Bank",
"Federal Bank",
"HDFC Bank",
"ICICI Bank",
"IDFC Bank",
"IndusInd Bank",
"Jammu and Kashmir Bank",
"Karnataka Bank",
"Karur Vysya Bank",
"Kotak Mahindra Bank",
"Lakshmi Vilas Bank",
"Nainital Bank",
"RBL Bank",
"South Indian Bank", 
"Tamilnad Mercantile Bank", 
"YES Bank"];

?>